# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMvq0eGEQJ5KoNCxPYu0DE5cZJ3bupVG
"""

nums=[1,1,2]
mylist=set()
count=0
for i in nums:
  if i not in mylist:
    mylist.add(i)
    nums[count]=i
    count+=1
print(count)

nums=[1,1,2]
j=1
for i in range(1,len(nums)):
  if nums[i]!=nums[i-1]:
    nums[j]=nums[i]
    j+=1
print(j)

nums=[0,1,2,2,3,0,4,2]
val=2
count=0
for i in range(0,len(nums)):
    if nums[i]!=val:
      count+=1
print(count)

