# -*- coding: utf-8 -*-
"""covid_toy1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukHrCVRynYLThpsuLXhdpLKzOQqHIidy
"""

import numpy as np
import pandas as pd

df=pd.read_csv('covid_toy.csv')
df

df['gender'].value_counts()

df['gender'] = df['gender'].map({'Female':0 , 'Male':1})

df

df['cough'].value_counts()

df['cough'] = df['cough'].map({'Mild':0 , 'Strong':1})

df

df.head()

df.tail()

df.describe()

df.info()

top_left_corner=df.iloc[:4,:3]
top_left_corner

s =   df.axes
s

p = df.dtypes
p

b = df.empty
b

df.isnull().sum()

df.dropna()

i=df.ndim
i

t=df.shape
t

d=df.size
d

a=df.values
a

p=df.sort_values(by = 'age')
p

df['Age'] = df['age'].astype(int)
df

df=df.drop(columns = ['Age'])

p=df
p['age'] = p['age'].astype(int)
p

df['age'] = df['age'].add(4)
df
df=df.drop(columns = ['Age'])
df

s=df.count()
s

p=df.max()
p

q=df.min()
q

r=df['age'].mean()
r

s=df['age'].median()
s

g=df.filter(items = ['age','gender'])
g

df[['age','gender']]

s=df.filter(items=[3,4,5,6],axis=0)
s

p=df.rename(columns={'age':'AGE',
                     'city':'CITY'} )
p

df.columns

df['half'] = df['age'].where (df['age']>18 , other=0)
df.head(10)

